### ISSUE TITLE
Exception! SyntaxError: Unexpected end of JSON input on send function

### ISSUE THREAD

**Issue by includeamin** [KaveNegar/kavenegar-node#4]
Exception! SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (****\Server\node_modules\kavenegar\kavenegar.js:36:27)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mohsenk** [comment]
I think this error is resolved in recent changes, If it's still there please open a new issue.
